---
title: Niche Packages in R
author: Maëlle Salmon and Scott Chamberlain
date: "`r Sys.Date()`"
output: md_document
---

```{r echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE
)
```

There are as of this writing 13,745 R packages on CRAN <https://cran.rstudio.com/web/packages/> 
and 1,649 packages on Bioconductor <https://bioconductor.org/packages/release/BiocViews.html#___Software>.
A small handful of these R packages get most of the downloads, usage, and attention, while most
of the other packages are used by few people. 

The widely used packages get lots of usage, surfacing bugs, improving the software. 

How do the less widely used, "niche packages", strive for the quality that comes somewhat
naturally when software is widely used? Why is it important for niche packages to survive
and be of high quality?

### What is a niche package?

There's many ways this could be defined. For our purposes we define niche packages as xxx

### Why niche packages are important

- Even if only 10 people use a package, it may be crucial to the work of those 10 people
- in an ideal world every piece of software is of highest quality possible, why shouldn't this be the case for niche packages as well
- likely that maintainers of niche packages have little time to work on them
- ...

### What does the data say?

look at the data

highlight ropensci pkgs

### Sustainability of niche packages

- don't have "many eyes surface bugs" of large projects, so how do you get that effect?
- maintainer should be a domain expert, so at least you have one power user

### More niche packages!

make more niche packages!
